language: c
compiler:
  - gcc

before_script:
  - sudo add-apt-repository -y ppa:fkrull/deadsnakes
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y python3.4 python3 gcc-4.7

script:
  - make -C unix CC=gcc-4.7
  - cd tests && MICROPY_CPYTHON3=python3.4 ./run-tests

after_failure: for exp in *.exp; do testbase=$(basename $exp .exp); echo -e "\nFAILURE $testbase"; diff $testbase.exp $testbase.out; done
